package com.docsearch.model;

import jakarta.persistence.*;
import lombok.*;

import java.time.Instant;

/**
 * Entity class that represents a stored document in the system.
 * <p>
 * This entity maps to the {@code documents} table in the database and
 * stores metadata (filename, content type, description, uploaded time)
 * along with the extracted text content of the document.
 */
@Entity
@Table(name = "documents")
@Getter @Setter
@Builder @NoArgsConstructor @AllArgsConstructor
public class DocumentEntity {

    /**
     * Unique identifier for the document.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The original name of the uploaded file.
     */
    private String filename;

    /**
     * MIME type of the uploaded file (e.g., text/plain, application/pdf).
     */
    private String contentType;

    /**
     * Extracted text content of the document.
     * Stored as a large text field in the database.
     */
    @Column(columnDefinition = "TEXT")
    private String contentText;

    /**
     * Optional user-provided description of the document.
     */
    private String description;

    /**
     * Timestamp indicating when the document was uploaded.
     */
    private Instant uploadedAt;
}
